Q.1 Create the NumPy array with values (1,2,3).
Create a second Numpy array with values (4,5,6).
Perform simple arithmetic operations on these two Numpy arrays:
a. Addition
b. Subtraction
c. Multiplication
d. Division

In [6]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#Addition
addition = array1 + array2
print("Addition =")
print(addition)

# Subtraction
subtraction = array1 - array2
print("\nSubtraction =")
print(subtraction)

# Multiplication
multiplication = array1 * array2
print("\nMultiplication =")
print(multiplication)

# Division 
division = array1 / array2
print("\nDivision =")
print(division)


Addition =
[5 7 9]

Subtraction =
[-3 -3 -3]

Multiplication =
[ 4 10 18]

Division =
[0.25 0.4  0.5 ]


Q.2. Create a Numpy array between values 10-90 and set the shape to be 3*3

a. Extract only the 3rd column from the Numpy array.

b. Extract only the 2nd row from the Numpy array

c. Extract those cells at the intersection of first two rows and first two columns.

In [7]:
array3 = np.arange(10, 91, 10).reshape(3, 3)

print("The 3x3 Array:")
print(array3)


The 3x3 Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
# a. Extract only the 3rd column
third_column = array3[:, 2]
print("\nExtracted 3rd Column:")
print(third_column)

# b. Extract only the 2nd row
second_row = array3[1, :]
print("\nExtracted 2nd Row:")
print(second_row)

# c. Extract cells at the intersection of first two rows and first two columns
intersection_cells = array3[:2, :2]
print("\nExtracted Cells at Intersection of First Two Rows and First Two Columns:")
print(intersection_cells)


Extracted 3rd Column:
[30 60 90]

Extracted 2nd Row:
[40 50 60]

Extracted Cells at Intersection of First Two Rows and First Two Columns:
[[10 20]
 [40 50]]


Q.3. Create a dictionary with 4 items and convert it into panda’s series. Create Dictionary of  Pandas series Convert above dictionary into data frame Slice last 2 rows from the data frame Slice a column from the data frame Create dictionary of tuples. Convert it into dataframe

In [1]:
import pandas as pd

panda_dict = {'Name': 'Shweta', 'Surname' : 'Kanungo','City': 'New York', 'Work': 'Professor'}

# Converting into Pandas Series
series_data = pd.Series(panda_dict)
print("Pandas Series:")
print(series_data)

# Create a dictionary of Pandas Series
data_dict_series = {'Name': pd.Series(['Sarvesh', 'Shweta', 'Rajat']),
                    'Surname': pd.Series(['Kanungo','K', 'Khanna' ]),
                    'City': pd.Series(['New York', 'London', 'Paris']),
                    'Work': pd.Series(['Advocate', 'Professor', 'Consultant'])}

# Convert the dictionary of Pandas Series into a DataFrame
df = pd.DataFrame(data_dict_series)
print("\nDataFrame:")
print(df)

# Slice last 2 rows from the data frame
last_two_rows = df.tail(2)
print("\nLast 2 Rows:")
print(last_two_rows)

# Slice a column from the data frame
selected_column = df['Name']
print("\nSelected Column ('Name'):")
print(selected_column)

# Create a dictionary of tuples
data_dict_tuples = {'Name': ('Sarvesh', 'Shweta', 'Rajat'),
                    'Surname': ('Kanungo','K', 'Khanna'),
                    'City': ('New York', 'London', 'Paris'),
                    'Work': ('Advocate', 'Professor', 'Consultant')}

# Convert the dictionary of tuples into a DataFrame
df_tuples = pd.DataFrame(data_dict_tuples)
print("\nDataFrame from Dictionary of Tuples:")
print(df_tuples)


Pandas Series:
Name          Shweta
Surname      Kanungo
City        New York
Work       Professor
dtype: object

DataFrame:
      Name  Surname      City        Work
0  Sarvesh  Kanungo  New York    Advocate
1   Shweta        K    London   Professor
2    Rajat   Khanna     Paris  Consultant

Last 2 Rows:
     Name Surname    City        Work
1  Shweta       K  London   Professor
2   Rajat  Khanna   Paris  Consultant

Selected Column ('Name'):
0    Sarvesh
1     Shweta
2      Rajat
Name: Name, dtype: object

DataFrame from Dictionary of Tuples:
      Name  Surname      City        Work
0  Sarvesh  Kanungo  New York    Advocate
1   Shweta        K    London   Professor
2    Rajat   Khanna     Paris  Consultant


Q.4. Explain the use of NumPy library along with
the Data structures in NumPy.

Ans. NumPy is the fundamental package for scientific computing in Python.
It is a Python library that provides a multidimensional array object, various derived objects
(such as masked arrays and matrices), and an assortment of routines for fast operations on
arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete
Fourier transforms, basic linear algebra, basic statistical operations, random simulation and
much more.

The main data structure in NumPy is the ndarray:

In [2]:
#Creating Numpy array
import numpy as np
np.array([2,4,56,422,32,1]) # 1D array


array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2,4,56,422,32,1]) #Vector
print(a)
type(a)

[  2   4  56 422  32   1]


numpy.ndarray

In [5]:
# 2D Array ( Matrix)
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)


[[45 34 22  2]
 [24 55  3 22]]


In [6]:
# 3 D ---- # Tensor
np.array ([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

array from ones & Zeros:

In [9]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# Another Type ---> random()
np.random.random((4,3))


array([[0.9238881 , 0.16531503, 0.35594236],
       [0.02849104, 0.2004666 , 0.83938135],
       [0.99752983, 0.12692091, 0.99079452],
       [0.53034152, 0.2906837 , 0.43008672]])

Indexing and Slicing:

In [13]:
arr_1d = np.array([0, 1, 2, 3, 4, 5])

# Indexing: Accessing a single element
first_element = arr_1d[0]
third_element = arr_1d[2]

print("1D Array:", arr_1d)
print("First Element:", first_element)
print("Third Element:", third_element)

# Creating a 2D array
arr_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# Indexing: Accessing a single element in a 2D array
element_2d = arr_2d[1, 2]

print("\n2D Array:")
print(arr_2d)
print("Element at (1, 2):", element_2d)

# Slicing: Extracting subarrays
slice_1d = arr_1d[2:5]  # Elements from index 2 to 4
slice_2d = arr_2d[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2

print("\nSliced 1D Array:", slice_1d)
print("Sliced 2D Array:")
print(slice_2d)


1D Array: [0 1 2 3 4 5]
First Element: 0
Third Element: 2

2D Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Element at (1, 2): 5

Sliced 1D Array: [2 3 4]
Sliced 2D Array:
[[1 2]
 [4 5]]


scalar operations:
Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication
on each element of a Numpy array.


In [16]:
new = np.array([[45,34,22,2],[24,55,3,22]])
new+1


array([[44, 33, 21,  1],
       [23, 54,  2, 21]])

relational Operators
The relational operators are also known as comparison operators, their main function is to
return either a true or false based on the value of operands.

In [17]:
new > 20

array([[ True,  True,  True, False],
       [ True,  True, False,  True]])

Beside above Numpy provides so many operations and  functions.In summary, NumPy is a fundamental library for numerical computing in Python, offering powerful data structures and operations that are essential for various scientific and engineering applications. Its efficient array operations and mathematical functions make it a go-to choice for tasks involving numerical data.

Q.5. Explain the use of Pandas library along with the Data structures in Pandas.

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.
Main Features:
1. Data Wrangling
2. Modeling
3. Visualization
4. High Performance Computing
5. Text Processing
6. Statistical Computing
7. Numerical Computing

The two primary data structures in Pandas are the Series and DataFrame.

Series:

A Series is a one-dimensional labeled array capable of holding any data type.
It can be created from a list, NumPy array, or dictionary.
Each element in a Series has a label (index) associated with it, making it easy to access and manipulate data.

DataFrame:

A DataFrame is a two-dimensional labeled data structure with columns that can be of different data types.
It can be thought of as an in-memory 2D table (like a spreadsheet or SQL table) with labeled axes (rows and columns).
DataFrames can be created from lists, dictionaries, NumPy arrays, and other DataFrame objects.

In [2]:
#Series:
import pandas as pd

# Creating a Pandas Series
series = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
series

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
#DataFrame:
import numpy as np
data={'a':pd.Series(np.random.randint(10,20,5)),
      'b':pd.Series(np.random.randint(5,8,5)),
      'c':pd.Series(5,index=[0,1,2])}
data

{'a': 0    17
 1    18
 2    12
 3    19
 4    19
 dtype: int32,
 'b': 0    6
 1    7
 2    7
 3    6
 4    7
 dtype: int32,
 'c': 0    5
 1    5
 2    5
 dtype: int64}

In [4]:
# Converting Dictionary of Pandas Series to DataFarme
df=pd.DataFrame(data)
df

a  b    c
0  17  6  5.0
1  18  7  5.0
2  12  7  5.0
3  19  6  NaN
4  19  7  NaN

DataFrames can be created from various data sources, such as NumPy arrays, dictionaries, CSV files, SQL databases, and more.

Data Manipulation:

Pandas provides powerful tools for data manipulation, including filtering, sorting, grouping, and merging. These operations enable users to clean and preprocess data efficiently.

In [ ]:
# Filtering and selecting data
df_filtered = df[df['A'] > 0]

# Grouping data
grouped_data = df.groupby('E').sum()


Missing Data Handling:

Pandas handles missing data gracefully, providing methods for filling, dropping, or interpolating missing values.

In [11]:
# Handling missing data
df_filled = df.fillna(0)


Time Series Analysis:

Pandas is widely used for time series analysis due to its support for date and time data. It provides functionalities for resampling, time zone handling, and date range generation.

In [12]:
# Time series analysis
date_rng = pd.date_range('2022-01-01', periods=6, freq='D')
df_time_series = pd.DataFrame(date_rng, columns=['date'])


Input/Output:

Pandas supports reading and writing data in various formats, including CSV, Excel, SQL databases, and more. This makes it easy to integrate with other data storage and processing tools.

In [ ]:
# Reading and writing data
df.to_csv('output.csv', index=False)
df_read = pd.read_csv('input.csv')


In [ ]:
### Statistical Operations on Pandas Dataframe

In [16]:
df1 = pd.DataFrame(
{"a" : [1 ,2, 3,7],
"b" : [4, 5, 6,8],
"c" : [7, 8, 9,9],
"d" : [1, 7, 9,0],
"e" : [8, 9, 9,1]
},
index = [10, 2, 3,4])
df1

a  b  c  d  e
10  1  4  7  1  8
2   2  5  8  7  9
3   3  6  9  9  9
4   7  8  9  0  1

In [17]:
# Find Mean
df1.mean()

a    3.25
b    5.75
c    8.25
d    4.25
e    6.75
dtype: float64

Plotting:

In [ ]:
# Plotting
df.plot(x='A', y='C', kind='scatter')


### Submitted By:

# Shweta Kanungo